name: Check for update and release

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/ci.yml@v3
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "qbittorrent"
      release_type: "script"
    secrets:
      repo_scoped_token: ${{ secrets.repo_scoped_token }}
